#!/usr/bin/env bash

set -euo pipefail

usage(){
    cat <<END
usage: rtorrent-magnet MAGNET-TEXT
END
}

getWatchDirectory(){
    rtxmlrpc method.get=",cfg.watch"
}

if [[ $# -lt 1 ]]; then
    usage
fi

if [[ "$1" =~ xt=urn:btih:([^&/]+) ]]; then

	destdir="$(getWatchDirectory)/start"
    tofile="$destdir/meta-${BASH_REMATCH[1]}.torrent"

    echo "Writing to file: $tofile"
	echo "d10:magnet-uri${#1}:${1}e" > "$tofile"
else
	echo "\"$1\" does not look like a magnet link, ignoring" >&2
	exit 1
fi
